credentials:
  usernames:
    demo_user:
      email: demo@example.com
      name: Demo User
      password: "$2b$12$ays96g56VZmTKK7ul9g0/OuuMlLdJavqcBSqZimD37A29YIKcvC52" 
cookie:
  name: streamlit_auth
  key: secret_cookie_key_abc123
  expiry_days: 1
